# Generated by Django 4.1.4 on 2022-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=25, verbose_name='Имя пользователя в Telegram')),
            ],
            options={
                'verbose_name': 'Профиль Telegram',
                'verbose_name_plural': 'Профили Telegram',
            },
        ),
    ]
