version: '3.9'
services:

  backend_django:
    container_name: Django-backend
    build: ./
    working_dir: /app/backend_django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  telegram_bot:
    build: ./
    container_name: TelegramBot
    working_dir: /app/telegram_bot
    command: python main.py
    restart: always
    depends_on:
      - backend_django

  db:
    image: mysql:8.0
    container_name: Database
    restart: always
    ports:
      - 13306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'project_db'
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  
  celery:
    build: ./
    container_name: Celery
    working_dir: /app/backend_django
    command: celery -A backend_django worker -B

    depends_on:
      - backend_django
      - redis

  redis:
    image: redis:7.0.7
    container_name: Redis
    command: redis-server
    restart: always
    ports:
      - 6379:6379

volumes:
  database: