# Generated by Django 4.1.4 on 2022-12-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='MonitoredCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_price', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='Ожидаемая стоимость')),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_app.coin', verbose_name='ID криптовалюты')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.telegramprofile', verbose_name='ID пользователя Telegram')),
            ],
            options={
                'verbose_name': 'Отслеживаемая криптовалюта',
                'verbose_name_plural': 'Отслеживаемые криптовалюты',
                'unique_together': {('user_id', 'coin_id')},
            },
        ),
    ]
