# Generated by Django 4.1.4 on 2022-12-26 05:33

from django.db import migrations
from requests import request


def add_coin(apps, schema_editor):
    Coin = apps.get_model('coin_app', 'Coin')
    with open('coins.txt', encoding="utf-8") as coins:
        response = request('GET', f'https://api.binance.com/api/v3/ticker/price?symbols={coins.read()}')
        coins_courses = response.json()
    coins = [
        Coin(name=coin['symbol'].replace('USDT', '', 1), price=coin['price'])
        for coin in sorted(coins_courses, key=lambda x: x['symbol'])
        ]
    Coin.objects.bulk_create(coins)

class Migration(migrations.Migration):

    dependencies = [
        ('coin_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_coin),
    ]
